# Generated by Django 3.1 on 2020-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='profile_url',
            field=models.URLField(default='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png', max_length=250),
        ),
    ]
