# Generated by Django 3.1 on 2020-11-07 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_hero_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.CharField(max_length=60)),
                ('story', models.CharField(max_length=600)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pic_url', models.URLField(default='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png', max_length=250)),
            ],
        ),
    ]
